"""empty message

Revision ID: 5bd0fccd40ef
Revises: 4be795bf41d1
Create Date: 2020-05-18 23:04:01.389850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd0fccd40ef'
down_revision = '4be795bf41d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_actors',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    op.drop_constraint('actors_movie_id_fkey', 'actors', type_='foreignkey')
    op.drop_column('actors', 'movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('actors_movie_id_fkey', 'actors', 'movies', ['movie_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_table('movie_actors')
    # ### end Alembic commands ###
